### ISSUE TITLE
Fails to create ImageBuilder resource due to deprecated image

### ISSUE THREAD

**Issue by juluriaj** [aws-samples/getting-started-with-amazon-appstream2-workshop-template#1]
Resource handler returned message: "The image AppStream-WinServer2019-03-03-2022 is DEPRECATED. The image must be in an AVAILABLE state for this action to succeed. (Service: AmazonAppStream; Status Code: 400; Error Code: ResourceNotAvailableException; Request ID: xxx; Proxy: null)" (RequestToken: xxx, HandlerErrorCode: GeneralServiceException)

**Comment by js37** [comment]
Thanks for reporting this. I have updated the image builder to AppStream-WinServer2019-03-29-2023
