### ISSUE TITLE
Fails to create ImageBuilder resource due to deprecated image

### ISSUE THREAD

**Issue by bouvs** [aws-samples/getting-started-with-amazon-appstream2-workshop-template#2]
Resource handler returned message: "The image AppStream-WinServer2019-03-29-2023 is DEPRECATED. The image must be in an AVAILABLE state for this action to succeed. (Service: AmazonAppStream; Status Code: 400; Error Code: ResourceNotAvailableException; Request ID: xxx; Proxy: null)" (RequestToken: xxx, HandlerErrorCode: GeneralServiceException)

Refering to [https://docs.aws.amazon.com/appstream2/latest/developerguide/base-image-version-history.html](https://docs.aws.amazon.com/appstream2/latest/developerguide/base-image-version-history.html), please update Base Image to AppStream-WinServer2019-11-13-2023.

**Comment by js37** [comment]
Updated the image builder. Thanks for letting me know.
